/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_viewer-test.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "./parser/s21_affine_transformations.h"
#include "./parser/s21_parsing_file.h"
#define SUCCESS 1
#define FAILURE 0
#define E 1e-7

int s21_eq_matrix(st_matrix *A, st_matrix *B) {
    int error = SUCCESS;
    for (int i = 0; i < A->rows && error != 0; ++i) {
        for (int j = 0; j < A->columns && error != 0; ++j) {
            if (fabs(A->matrix[i][j] - B->matrix[i][j]) >= E) {
                error = FAILURE;
            }
        }
    }
    return error;
}

START_TEST(viewer_1) {
#line 46
    st_data data;
    FILE *file = fopen("./obj/test.obj", "r");
    s21_parsing_file(&data, file);

    st_data prov;
    FILE *fil = fopen("./obj/test.obj", "r");
    s21_parsing_file(&prov, fil);

    for (int i = 0; i < 8; i++) {
        int res = s21_eq_matrix(&data.matrix_3d[i], &prov.matrix_3d[i]);
        ck_assert_int_eq(res, 1);
    }

    for (int i = 0; i < 12; ++i) {
        for (int j = 0; j < 3; ++j) {
            ck_assert_int_eq(data.polygons[i].vert[j], prov.polygons[i].vert[j]);
        }
    }
    moving(&data, 2, 2, 2);
    moving(&prov, 2, 2, 2);
    for (int i = 0; i < 8; i++) {
        int res = s21_eq_matrix(&data.matrix_3d[i], &prov.matrix_3d[i]);
        ck_assert_int_eq(res, 1);
    }

    for (int i = 0; i < 12; ++i) {
        for (int j = 0; j < 3; ++j) {
            ck_assert_int_eq(data.polygons[i].vert[j], prov.polygons[i].vert[j]);
        }
    }
    resize(&data, 2, 2, 2);
    resize(&prov, 2, 2, 2);
    for (int i = 0; i < 8; i++) {
        int res = s21_eq_matrix(&data.matrix_3d[i], &prov.matrix_3d[i]);
        ck_assert_int_eq(res, 1);
    }

    for (int i = 0; i < 12; ++i) {
        for (int j = 0; j < 3; ++j) {
            ck_assert_int_eq(data.polygons[i].vert[j], prov.polygons[i].vert[j]);
        }
    }
    rotation(&data, 2, 2, 2);
    rotation(&prov, 2, 2, 2);
    for (int i = 0; i < 8; i++) {
        int res = s21_eq_matrix(&data.matrix_3d[i], &prov.matrix_3d[i]);
        ck_assert_int_eq(res, 1);
    }

    for (int i = 0; i < 12; ++i) {
        for (int j = 0; j < 3; ++j) {
            ck_assert_int_eq(data.polygons[i].vert[j], prov.polygons[i].vert[j]);
        }
    }
    s21_remove_struct_matrix(&data);
    s21_remove_polygons(&data);
    s21_remove_struct_matrix(&prov);
    s21_remove_polygons(&prov);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, viewer_1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
