/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_tests.check" instead.
 */

#include <check.h>

#line 1 "s21_tests.check"
#include <check.h>

#include "s21_calc.h"
#include "s21_parsing.h"
#define E 1e-7

START_TEST(calc_1) {
#line 8
    ck_assert_double_nan(parsing("7/0", "0"));
}
END_TEST

START_TEST(calc_2) {
#line 11
    ck_assert_double_nan(parsing("7/x", "0"));
}
END_TEST

START_TEST(calc_3) {
#line 14
    ck_assert_double_nan(parsing("5/(7.5-x)", "7.5"));
}
END_TEST

START_TEST(calc_4) {
#line 17
    ck_assert_double_eq(parsing("0/7", "0"), 0.0);
}
END_TEST

START_TEST(calc_5) {
#line 20
    ck_assert_double_eq(parsing("log(10)", "0"), 1.0);
}
END_TEST

START_TEST(calc_6) {
#line 23
    double calc = parsing("ln(10)", "0");
    double res = 2.3025850;
    double result = fabs(calc - res);
    int prov = 1;
    if (result >= E) {
        prov = 0;
    }
    ck_assert_int_eq(prov, 1);
}
END_TEST

START_TEST(calc_7) {
#line 33
    double calc = parsing("cos(90)", "0");
    double res = -0.4480736;
    double result = fabs(calc - res);
    int prov = 1;
    if (result >= E) {
        prov = 0;
    }
    ck_assert_int_eq(prov, 1);
}
END_TEST

START_TEST(calc_8) {
#line 42
    double calc = parsing("sin(90)", "0");
    double res = 0.8939966;
    double result = fabs(calc - res);
    int prov = 1;
    if (result >= E) {
        prov = 0;
    }
    ck_assert_int_eq(prov, 1);
}
END_TEST

START_TEST(calc_9) {
#line 52
    double calc = parsing("tan(1)", "0");
    double res = 1.5574077;
    double result = fabs(calc - res);
    int prov = 1;
    if (result >= E) {
        prov = 0;
    }
    ck_assert_int_eq(prov, 1);
}
END_TEST

START_TEST(calc_10) {
#line 62
    double calc = parsing("asin(0.5)", "0");
    double res = 0.5235988;
    double result = fabs(calc - res);
    int prov = 1;
    if (result >= E) {
        prov = 0;
    }
    ck_assert_int_eq(prov, 1);
}
END_TEST

START_TEST(calc_11) {
#line 72
    double calc = parsing("acos(0.5)", "0");
    double res = 1.0471976;
    double result = fabs(calc - res);
    int prov = 1;
    if (result >= E) {
        prov = 0;
    }
    ck_assert_int_eq(prov, 1);
}
END_TEST

START_TEST(calc_12) {
#line 82
    ck_assert_double_eq(parsing("4^15", "0"), 1073741824.0);
}
END_TEST

START_TEST(calc_13) {
#line 85
    ck_assert_double_eq(parsing("sqrt(144)", "0"), 12);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, calc_1);
    tcase_add_test(tc1_1, calc_2);
    tcase_add_test(tc1_1, calc_3);
    tcase_add_test(tc1_1, calc_4);
    tcase_add_test(tc1_1, calc_5);
    tcase_add_test(tc1_1, calc_6);
    tcase_add_test(tc1_1, calc_7);
    tcase_add_test(tc1_1, calc_8);
    tcase_add_test(tc1_1, calc_9);
    tcase_add_test(tc1_1, calc_10);
    tcase_add_test(tc1_1, calc_11);
    tcase_add_test(tc1_1, calc_12);
    tcase_add_test(tc1_1, calc_13);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
