/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_string-test.check" instead.
 */

#include <check.h>

#line 1 "s21_string-test.check"
#include "s21_string.h"
#include <stdlib.h>
#include <string.h>

// caquaman
// start memset tests
START_TEST(s21_memset_test_1_str) {
#line 8
    char str1[5] = "1111";
    char str2[5] = "1111";
    ck_assert_str_eq(s21_memset(str1, '0', 2), memset(str2, '0', 2));
// start strchr tests
}
END_TEST

START_TEST(s21_strchr_test_1) {
#line 13
    char *str = "Hello World!";
    char *ptr1 = s21_strchr(str, 'l');
    char *ptr2 = strchr(str, 'l');
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strchr_test_2) {
#line 19
    char *str = "Hello World!";
    char *ptr1 = s21_strchr(str, 'o');
    char *ptr2 = strchr(str, 'o');
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strchr_test_3) {
#line 25
    char *str = "Hello World!";
    char *ptr1 = s21_strchr(str, 'c');
    char *ptr2 = strchr(str, 'c');
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strchr_test_4) {
#line 30
    char *str = "";
    char *ptr1 = s21_strchr(str, 'c');
    char *ptr2 = strchr(str, 'c');
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strchr_test_5) {
#line 35
    char *str = "Hello World!";
    char *ptr1 = s21_strchr(str, '!');
    char *ptr2 = strchr(str, '!');
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strchr_test_6) {
#line 40
    char *str = "Hello World!";
    char *ptr1 = s21_strchr(str, '\0');
    char *ptr2 = strchr(str, '\0');
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
// start strcpy tests
}
END_TEST

START_TEST(s21_strcpy_test_1) {
#line 47
    char *str1 = "Hello World";
    char *str2 = (char*)malloc(sizeof(str1));
    char *str3 = (char*)malloc(sizeof(str1));
    s21_strcpy(str2, str1);
    strcpy(str3, str1);
    ck_assert_str_eq(str2, str3);
    free(str2);
    free(str3);
}
END_TEST

START_TEST(s21_strcpy_test_2) {
#line 56
    char *str1 = "Hello";
    char *str2 = (char*)malloc(sizeof(str1));
    char *str3 = (char*)malloc(sizeof(str1));
    s21_strcpy(str2, str1);
    strcpy(str3, str1);
    ck_assert_str_eq(str2, str3);
    free(str2);
    free(str3);
}
END_TEST

START_TEST(s21_strcpy_test_3) {
#line 65
    char *str1 = "";
    char *str2 = (char*)malloc(sizeof(str1));
    char *str3 = (char*)malloc(sizeof(str1));
    s21_strcpy(str2, str1);
    strcpy(str3, str1);
    ck_assert_str_eq(str2, str3);
    free(str2);
    free(str3);
}
END_TEST

START_TEST(s21_strcpy_test_4) {
#line 74
    char *str1 = "Hello";
    char str2[6];
    char str3[6];
    s21_strcpy(str2, str1);
    strcpy(str3, str1);
    ck_assert_str_eq(str2, str3);
// start strerror tests
}
END_TEST

START_TEST(s21_strerror_test_1) {
#line 82
    for (int i = -2; i < LAST_NUM_ERR + 2; i++)
        ck_assert_str_eq(s21_strerror(i), strerror(i));
// gconn
// start strncat tests
}
END_TEST

START_TEST(s21_strncat_test_1) {
#line 87
    char str1[20] = "As cool as ";
    char str2[20] = "As cool as ";
    char src[] = "a duck";
    ck_assert_str_eq(s21_strncat(str1, src, 10), strncat(str2, src, 10));
}
END_TEST

START_TEST(s21_strncat_test_2) {
#line 92
    char str1[13] = "Cool ";
    char str2[13] = "Cool ";
    char src[] = "duck";
    ck_assert_str_eq(s21_strncat(str1, src, 3), strncat(str2, src, 3));
}
END_TEST

START_TEST(s21_strncat_test_3) {
#line 97
    char str1[11] = "";
    char str2[11] = "";
    char src[] = "I'm a duck";
    char *res1 = s21_strncat(str1, src, 11);
    char *res2 = strncat(str2, src, 11);
    ck_assert_str_eq(res1, res2);
}
END_TEST

START_TEST(s21_strncat_test_4) {
#line 104
    char str1[] = "Who am i?";
    char str2[] = "Who am i?";
    char src[] = "";
    ck_assert_str_eq(s21_strncat(str1, src, 10), strncat(str2, src, 10));
}
END_TEST

START_TEST(s21_strncat_test_5) {
#line 109
    char str1[1] = "";
    char str2[1] = "";
    char src[1] = "";
    ck_assert_str_eq(s21_strncat(str1, src, 1), strncat(str2, src, 1));
// start strcmp tests
}
END_TEST

START_TEST(s21_strcmp_test_1) {
#line 115
    char *str1 = "Hey";
    char *str2 = "Hey";
    ck_assert_int_eq(s21_strcmp(str1, str2), strcmp(str1, str2));
}
END_TEST

START_TEST(s21_strcmp_test_2) {
#line 119
    char *str1 = "";
    char *str2 = "Hey";
    ck_assert_int_eq(s21_strcmp(str1, str2), strcmp(str1, str2));
}
END_TEST

START_TEST(s21_strcmp_test_3) {
#line 123
    char *str1 = "Hey";
    char *str2 = "";
    ck_assert_int_eq(s21_strcmp(str1, str2), strcmp(str1, str2));
}
END_TEST

START_TEST(s21_strcmp_test_4) {
#line 127
    char *str1 = "Ahoi";
    char *str2 = "Babe";
    ck_assert_int_eq(s21_strcmp(str1, str2), strcmp(str1, str2));
}
END_TEST

START_TEST(s21_strcmp_test_5) {
#line 131
    char *str1 = "Babe";
    char *str2 = "Ahoi";
    ck_assert_int_eq(s21_strcmp(str1, str2), strcmp(str1, str2));
// start strspn tests
}
END_TEST

START_TEST(s21_strspn_test_1) {
#line 136
    char *str1 = "Hey";
    char *str2 = "Hey";
    ck_assert_int_eq(s21_strspn(str1, str2), strspn(str1, str2));
}
END_TEST

START_TEST(s21_strspn_test_2) {
#line 140
    char *str1 = "";
    char *str2 = "Hey";
    ck_assert_int_eq(s21_strspn(str1, str2), strspn(str1, str2));
}
END_TEST

START_TEST(s21_strspn_test_3) {
#line 144
    char *str1 = "";
    char *str2 = "Hey";
    ck_assert_int_eq(s21_strspn(str2, str1), strspn(str2, str1));
}
END_TEST

START_TEST(s21_strspn_test_4) {
#line 148
    char *str1 = "HeHello friend";
    char *str2 = "Hello";
    ck_assert_int_eq(s21_strspn(str1, str2), strspn(str1, str2));
}
END_TEST

START_TEST(s21_strspn_test_5) {
#line 152
    char *str1 = "Friend";
    char *str2 = "Hello";
    ck_assert_int_eq(s21_strspn(str1, str2), strspn(str1, str2));
// start strstr tests
}
END_TEST

START_TEST(s21_strstr_test_1) {
#line 157
    char *str1 = "Hey";
    char *str2 = "Hey";
    ck_assert_str_eq(s21_strstr(str1, str2), strstr(str1, str2));
}
END_TEST

START_TEST(s21_strstr_test_2) {
#line 161
    char *str1 = "Hey Hey";
    char *str2 = "";
    ck_assert_str_eq(s21_strstr(str1, str2), strstr(str1, str2));
}
END_TEST

START_TEST(s21_strstr_test_3) {
#line 165
    char *str1 = "";
    char *str2 = "Hey";
    fail_unless(s21_strstr(str1, str2) == strstr(str1, str2));
}
END_TEST

START_TEST(s21_strstr_test_4) {
#line 169
    char *str1 = "Hello friend";
    char *str2 = "Hey";
    fail_unless(s21_strstr(str1, str2) == strstr(str1, str2));
// start strtok tests
}
END_TEST

START_TEST(s21_strtok_test_1) {
#line 174
    char str1[] = "Hey";
    char str2[] = "Hey";
    char denim[] = " ";
    ck_assert_str_eq(s21_strtok(str1, denim), strtok(str2, denim));
}
END_TEST

START_TEST(s21_strtok_test_2) {
#line 179
    char str1[] = "Hey Hey";
    char str2[] = "Hey Hey";
    char denim[] = " ";
    ck_assert_str_eq(s21_strtok(str1, denim), strtok(str2, denim));
}
END_TEST

START_TEST(s21_strtok_test_3) {
#line 184
    char str1[] = "Hey, Hey";
    char str2[] = "Hey, Hey";
    char denim[] = " ,";
    ck_assert_str_eq(s21_strtok(str1, denim), strtok(str2, denim));
}
END_TEST

START_TEST(s21_strtok_test_4) {
#line 189
    char str1[] = "Hey, Hey";
    char str2[] = "Hey, Hey";
    char denim[] = " ,";
    ck_assert_str_eq(s21_strtok(str1, denim), strtok(str2, denim));
    ck_assert_str_eq(s21_strtok(S21_NULL, denim), strtok(S21_NULL, denim));
}
END_TEST

START_TEST(s21_strtok_test_5) {
#line 195
    char str1[] = "";
    char str2[] = "";
    char denim[] = " ,";
    fail_unless(s21_strtok(str1, denim) == strtok(str2, denim));
}
END_TEST

START_TEST(s21_strtok_test_6) {
#line 200
    char str1[] = "Hey Hey";
    char str2[] = "Hey Hey";
    char denim[] = "";
    ck_assert_str_eq(s21_strtok(str1, denim), strtok(str2, denim));
// sperses
// start memchr tests
}
END_TEST

START_TEST(s21_memchr_test_1_str) {
#line 207
    char *str1 = "Hello World";
    char *ptr1 = s21_memchr(str1, 'l', 12);
    char *ptr2 = memchr(str1, 'l', 12);
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_memchr_test_2_str) {
#line 213
    char *str1 = "Hello World";
    char *ptr1 = s21_memchr(str1, 'c', 12);
    char *ptr2 = memchr(str1, 'c', 12);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_memchr_test_3_str) {
#line 218
    char *str1 = "Hello World";
    char *ptr1 = s21_memchr(str1, 'd', 12);
    char *ptr2 = memchr(str1, 'd', 12);
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_memchr_test_4_str) {
#line 224
    char *str1 = "Hello World";
    char *ptr1 = s21_memchr(str1, '\0', 12);
    char *ptr2 = memchr(str1, '\0', 12);
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_memchr_test_5_str) {
#line 230
    char *str1 = "";
    char *ptr1 = s21_memchr(str1, 'c', 12);
    char *ptr2 = memchr(str1, 'c', 12);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_memchr_test_6_str) {
#line 235
    char *str1 = "Hello World";
    char *ptr1 = s21_memchr(str1, 'H', 12);
    char *ptr2 = memchr(str1, 'H', 12);
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
// start memcmp tests
}
END_TEST

START_TEST(s21_memcmp_test_1_str) {
#line 242
    char *str1 = "Hello World";
    char *str2 = "Hello World";
    ck_assert_int_eq(s21_memcmp(str1, str2, 12), memcmp(str1, str2, 12));
}
END_TEST

START_TEST(s21_memcmp_test_2_str) {
#line 246
    char *str1 = "Hello World";
    char *str2 = "Hello Worl";
    ck_assert_int_eq(s21_memcmp(str1, str2, 12), memcmp(str1, str2, 12));
}
END_TEST

START_TEST(s21_memcmp_test_3_str) {
#line 250
    char *str1 = "Hello Worl";
    char *str2 = "Hello World";
    ck_assert_int_eq(s21_memcmp(str1, str2, 12), memcmp(str1, str2, 12));
}
END_TEST

START_TEST(s21_memcmp_test_4_str) {
#line 254
    char *str1 = "";
    char *str2 = "";
    ck_assert_int_eq(s21_memcmp(str1, str2, 12), memcmp(str1, str2, 12));
}
END_TEST

START_TEST(s21_memcmp_test_5_str) {
#line 258
    char *str1 = "Hello World";
    char *str2 = "";
    ck_assert_int_eq(s21_memcmp(str1, str2, 12), memcmp(str1, str2, 12));
}
END_TEST

START_TEST(s21_memcmp_test_6_str) {
#line 262
    char *str1 = "";
    char *str2 = "Hello World";
    ck_assert_int_eq(s21_memcmp(str1, str2, 12), memcmp(str1, str2, 12));
}
END_TEST

START_TEST(s21_memcmp_test_7_str) {
#line 266
    char *str1 = "";
    char *str2 = "Hello World";
    ck_assert_int_eq(s21_memcmp(str1, str2, 0), memcmp(str1, str2, 0));
// start memmove tests
}
END_TEST

START_TEST(s21_memmove_test_1_str) {
#line 271
    char *str1 = "";
    char *ptr1 = (char*)malloc(sizeof(char) * 5);
    char *ptr2 = (char*)malloc(sizeof(char) * 5);
    ck_assert_str_eq(s21_memmove(ptr1, str1, 5), memmove(ptr2, str1, 5));
    free(ptr1);
    free(ptr2);
}
END_TEST

START_TEST(s21_memmove_test_2_str) {
#line 278
    char ptr1[6] = "1";
    char ptr2[6] = "1";
    char str1[6] = "Hello";
    ck_assert_str_eq(s21_memmove(ptr1, str1, 5), memmove(ptr2, str1, 5));
}
END_TEST

START_TEST(s21_memmove_test_3_str) {
#line 283
    char str1[6] = "Hello";
    char ptr1[6] = "1";
    char ptr2[6] = "1";
    ck_assert_str_eq(s21_memmove(ptr1, str1, 5), memmove(ptr2, str1, 5));
// start strcat tests
}
END_TEST

START_TEST(s21_strcat_test_1_str) {
#line 289
    char str1[14] = "Hello ";
    char str2[14] = "Hello ";
    char str3[6] = "World";
    ck_assert_str_eq(s21_strcat(str1, str3), strcat(str2, str3));
}
END_TEST

START_TEST(s21_strcat_test_2_str) {
#line 294
    char str1[14] = "";
    char str2[14] = "";
    char str3[6] = "World";
    ck_assert_str_eq(s21_strcat(str1, str3), strcat(str2, str3));
}
END_TEST

START_TEST(s21_strcat_test_3_str) {
#line 299
    char str1[14] = "Hello ";
    char str2[14] = "Hello ";
    char str3[6] = "";
    ck_assert_str_eq(s21_strcat(str1, str3), strcat(str2, str3));
}
END_TEST

START_TEST(s21_strcat_test_4_str) {
#line 304
    char str1[14] = "";
    char str2[14] = "";
    char str3[6] = "";
    ck_assert_str_eq(s21_strcat(str1, str3), strcat(str2, str3));
// ekala
// start strncmp tests
}
END_TEST

START_TEST(s21_strncmp_test_1) {
#line 311
    int n = 5;
    char str1[16] = "1234567890";
    char str2[16] = "1234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_2) {
#line 316
    int n = 5;
    char str1[16] = "1234567890";
    char str2[16] = "0234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_3) {
#line 321
    int n = 5;
    char str1[16] = "0234567890";
    char str2[16] = "1234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_4) {
#line 326
    int n = 5;
    char str1[16] = "";
    char str2[16] = "";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_5) {
#line 331
    int n = 5;
    char str1[16] = "1234567890";
    char str2[16] = "";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_6) {
#line 336
    int n = 5;
    char str1[16] = "";
    char str2[16] = "1234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_7) {
#line 341
    int n = 0;
    char str1[16] = "1234567890";
    char str2[16] = "1234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_8) {
#line 346
    int n = 5;
    char *str1 = "1234567890";
    char *str2 = "1234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_9) {
#line 351
    int n = 5;
    char *str1 = "0234567890";
    char *str2 = "1234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_10) {
#line 356
    int n = 5;
    char *str1 = "1234567890";
    char *str2 = "0234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_11) {
#line 361
    int n = 5;
    char *str1 = "";
    char *str2 = "";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_12) {
#line 366
    int n = 5;
    char *str1 = "1234567890";
    char *str2 = "";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_13) {
#line 371
    int n = 5;
    char *str1 = "";
    char *str2 = "0234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
}
END_TEST

START_TEST(s21_strncmp_test_14) {
#line 376
    int n = 0;
    char *str1 = "1234567890";
    char *str2 = "1234567890";
    ck_assert_int_eq(s21_strncmp(str1, str2, n), strncmp(str1, str2, n));
// start strcspn tests
}
END_TEST

START_TEST(s21_strcspn_test_1) {
#line 382
    char str[16] = "Hello";
    char sem[16] = "l";
    ck_assert_int_eq(s21_strcspn(str, sem), strcspn(str, sem));
}
END_TEST

START_TEST(s21_strcspn_test_2) {
#line 386
    char str[16] = "Hello";
    char sem[16] = "";
    ck_assert_int_eq(s21_strcspn(str, sem), strcspn(str, sem));
}
END_TEST

START_TEST(s21_strcspn_test_3) {
#line 390
    char str[16] = "";
    char sem[16] = "";
    ck_assert_int_eq(s21_strcspn(str, sem), strcspn(str, sem));
}
END_TEST

START_TEST(s21_strcspn_test_4) {
#line 394
    char str[16] = "";
    char sem[16] = "l";
    ck_assert_int_eq(s21_strcspn(str, sem), strcspn(str, sem));
}
END_TEST

START_TEST(s21_strcspn_test_5) {
#line 398
    char *str = "Hello";
    char *sem = "l";
    ck_assert_int_eq(s21_strcspn(str, sem), strcspn(str, sem));
}
END_TEST

START_TEST(s21_strcspn_test_6) {
#line 402
    char *str = "Hello";
    char *sem = "";
    ck_assert_int_eq(s21_strcspn(str, sem), strcspn(str, sem));
}
END_TEST

START_TEST(s21_strcspn_test_7) {
#line 406
    char *str = "";
    char *sem = "";
    ck_assert_int_eq(s21_strcspn(str, sem), strcspn(str, sem));
}
END_TEST

START_TEST(s21_strcspn_test_8) {
#line 410
    char *str = "";
    char *sem = "l";
    ck_assert_int_eq(s21_strcspn(str, sem), strcspn(str, sem));
// start strrchr tests
}
END_TEST

START_TEST(s21_strrchr_test_1) {
#line 415
    char str[15] = "Hello World";
    char *ptr1 = s21_strrchr(str, 'o');
    char *ptr2 = strrchr(str, 'o');
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strrchr_test_2) {
#line 421
    char str[15] = "";
    char *ptr1 = s21_strrchr(str, 'o');
    char *ptr2 = strrchr(str, 'o');
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strrchr_test_3) {
#line 426
    char str[15] = "Hello World0";
    char *ptr1 = s21_strrchr(str, 'o');
    char *ptr2 = strrchr(str, 'o');
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strrchr_test_4) {
#line 432
    char str[15] = "Hello World";
    char *ptr1 = s21_strrchr(str, '4');
    char *ptr2 = strrchr(str, '4');
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strrchr_test_5) {
#line 437
    char *str = "Hello World";
    char *ptr1 = s21_strrchr(str, 'o');
    char *ptr2 = strrchr(str, 'o');
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strrchr_test_6) {
#line 443
    char *str = "";
    char *ptr1 = s21_strrchr(str, 'o');
    char *ptr2 = strrchr(str, 'o');
    fail_unless(ptr1 == ptr2);
}
END_TEST

START_TEST(s21_strrchr_test_7) {
#line 448
    char *str = "Hello World0";
    char *ptr1 = s21_strrchr(str, 'o');
    char *ptr2 = strrchr(str, 'o');
    ck_assert_int_eq(*ptr1, *ptr2);
    fail_unless(ptr1 == ptr2);
// start strncpy tests
}
END_TEST

START_TEST(s21_strncpy_test_1) {
#line 455
    int n = 5;
    char dest1[16] = "Hello";
    char dest2[16] = "Hello";
    char src[16] = "World";
    ck_assert_str_eq(s21_strncpy(dest1, src, n), strncpy(dest2, src, n));
}
END_TEST

START_TEST(s21_strncpy_test_2) {
#line 461
    int n = 5;
    char dest1[16] = "Hell";
    char dest2[16] = "Hell";
    char src[16] = "World";
    ck_assert_str_eq(s21_strncpy(dest1, src, n), strncpy(dest2, src, n));
}
END_TEST

START_TEST(s21_strncpy_test_3) {
#line 467
    int n = 5;
    char dest1[16] = "Hello";
    char dest2[16] = "Hello";
    char src[16] = "Wok";
    ck_assert_str_eq(s21_strncpy(dest1, src, n), strncpy(dest2, src, n));
}
END_TEST

START_TEST(s21_strncpy_test_4) {
#line 473
    int n = 0;
    char dest1[16] = "Hello";
    char dest2[16] = "Hello";
    char src[16] = "World";
    ck_assert_str_eq(s21_strncpy(dest1, src, n), strncpy(dest2, src, n));
}
END_TEST

START_TEST(s21_strncpy_test_5) {
#line 479
    int n = 5;
    char dest1[16] = "Hello";
    char dest2[16] = "Hello";
    char src[16] = "";
    ck_assert_str_eq(s21_strncpy(dest1, src, n), strncpy(dest2, src, n));
}
END_TEST

START_TEST(s21_strncpy_test_6) {
#line 485
    int n = 5;
    char dest1[16] = "";
    char dest2[16] = "";
    char src[16] = "";
    ck_assert_str_eq(s21_strncpy(dest1, src, n), strncpy(dest2, src, n));
}
END_TEST

START_TEST(s21_strncpy_test_7) {
#line 491
    int n = 0;
    char dest1[16] = "";
    char dest2[16] = "";
    char src[16] = "";
    ck_assert_str_eq(s21_strncpy(dest1, src, n), strncpy(dest2, src, n));
// mabobbi
// start memcpy tests
}
END_TEST

START_TEST(s21_memcpy_test_1) {
#line 499
    int n = 5;
    char dest1[16] = "Hello";
    char dest2[16] = "Hello";
    char src[16] = "World";
    ck_assert_str_eq(s21_memcpy(dest1, src, n), memcpy(dest2, src, n));
}
END_TEST

START_TEST(s21_memcpy_test_2) {
#line 505
    int n = 5;
    char dest1[16] = "Hell";
    char dest2[16] = "Hell";
    char src[16] = "World";
    ck_assert_str_eq(s21_memcpy(dest1, src, n), memcpy(dest2, src, n));
}
END_TEST

START_TEST(s21_memcpy_test_3) {
#line 511
    int n = 5;
    char dest1[16] = "Hello";
    char dest2[16] = "Hello";
    char src[16] = "Wok";
    ck_assert_str_eq(s21_memcpy(dest1, src, n), memcpy(dest2, src, n));
}
END_TEST

START_TEST(s21_memcpy_test_4) {
#line 517
    int n = 0;
    char dest1[16] = "Hello";
    char dest2[16] = "Hello";
    char src[16] = "World";
    ck_assert_str_eq(s21_memcpy(dest1, src, n), memcpy(dest2, src, n));
}
END_TEST

START_TEST(s21_memcpy_test_5) {
#line 523
    int n = 5;
    char dest1[16] = "Hello";
    char dest2[16] = "Hello";
    char src[16] = "";
    ck_assert_str_eq(s21_memcpy(dest1, src, n), memcpy(dest2, src, n));
}
END_TEST

START_TEST(s21_memcpy_test_6) {
#line 529
    int n = 5;
    char dest1[16] = "";
    char dest2[16] = "";
    char src[16] = "";
    ck_assert_str_eq(s21_memcpy(dest1, src, n), memcpy(dest2, src, n));
}
END_TEST

START_TEST(s21_memcpy_test_7) {
#line 535
    int n = 0;
    char dest1[16] = "";
    char dest2[16] = "";
    char src[16] = "";
    ck_assert_str_eq(s21_memcpy(dest1, src, n), memcpy(dest2, src, n));
// start strlen tests
}
END_TEST

START_TEST(s21_strlen_test_1) {
#line 542
    char a[] = "HelloWorld";
    ck_assert_int_eq(s21_strlen(a), strlen(a));
}
END_TEST

START_TEST(s21_strlen_test_2) {
#line 545
    char b[30];
    ck_assert_int_eq(s21_strlen(b), strlen(b));
}
END_TEST

START_TEST(s21_strlen_test_3) {
#line 548
    char str[5] = "Hello";
    ck_assert_int_eq(s21_strlen(str), strlen(str));
}
END_TEST

START_TEST(s21_strlen_test_4) {
#line 551
     char *p = "Gul'dan";
     ck_assert_int_eq(s21_strlen(p), strlen(p));
// start strpbrk tests
}
END_TEST

START_TEST(s21_strpbrk_test_1) {
#line 555
    char *m = " Moz art's ";
    char *f_m = " ";
    ck_assert_str_eq(s21_strpbrk(m, f_m), strpbrk(m, f_m));
}
END_TEST

START_TEST(s21_strpbrk_test_2) {
#line 559
    char m[] = "Hello";
    char f_m[] = "";
    fail_unless(s21_strpbrk(m, f_m) == strpbrk(m, f_m));
}
END_TEST

START_TEST(s21_strpbrk_test_3) {
#line 563
    char str[10] = "\\Hello";
    char str1[10] = " le\\H";
    ck_assert_str_eq(s21_strpbrk(str, str1), strpbrk(str, str1));
    fail_unless(s21_strpbrk(str, str1) == strpbrk(str, str1));
}
END_TEST

START_TEST(s21_strpbrk_test_4) {
#line 568
    char *str = "HelloWorld";
    char str1[] = "W";
    ck_assert_str_eq(s21_strpbrk(str, str1), strpbrk(str, str1));
    fail_unless(s21_strpbrk(str, str1) == strpbrk(str, str1));
}
END_TEST

START_TEST(s21_strpbrk_test_5) {
#line 573
    char str[] = "PrivetMir";
    ck_assert_str_eq(s21_strpbrk(str, "e"), strpbrk(str, "e"));
}
END_TEST

START_TEST(s21_strpbrk_test_6) {
#line 576
    char str[] = "";
    char str1[] = "2";
    fail_unless(s21_strpbrk(str, str1) == strpbrk(str, str1));
// bonus
// start toupper tests
}
END_TEST

START_TEST(s21_toupper_test_1) {
#line 582
    char* str = "hello";
    char* ptr = (char*)s21_to_upper(str);
    ck_assert_str_eq(ptr, "HELLO");
    free(ptr);
}
END_TEST

START_TEST(s21_toupper_test_2) {
#line 587
    char* str = "";
    char* ptr = (char*)s21_to_upper(str);
    ck_assert_str_eq(ptr, "");
    free(ptr);
}
END_TEST

START_TEST(s21_toupper_test_3) {
#line 592
    char* str = "HeLLo";
    char* ptr = (char*)s21_to_upper(str);
    ck_assert_str_eq(ptr, "HELLO");
    free(ptr);
}
END_TEST

START_TEST(s21_toupper_test_4) {
#line 597
    char* str = "HELLO";
    char* ptr = (char*)s21_to_upper(str);
    ck_assert_str_eq(ptr, "HELLO");
    free(ptr);
}
END_TEST

START_TEST(s21_toupper_test_5) {
#line 602
    char* str = "!@#$%^&";
    char* ptr = (char*)s21_to_upper(str);
    ck_assert_str_eq(ptr, "!@#$%^&");
    free(ptr);
// start tolower tests
}
END_TEST

START_TEST(s21_tolower_test_1) {
#line 608
    char* str = "HELLO";
    char* ptr = (char*)s21_to_lower(str);
    ck_assert_str_eq(ptr, "hello");
    free(ptr);
}
END_TEST

START_TEST(s21_tolower_test_2) {
#line 613
    char* str = "";
    char* ptr = (char*)s21_to_lower(str);
    ck_assert_str_eq(ptr, "");
    free(ptr);
}
END_TEST

START_TEST(s21_tolower_test_3) {
#line 618
    char* str = "HeLLo";
    char* ptr = (char*)s21_to_lower(str);
    ck_assert_str_eq(ptr, "hello");
    free(ptr);
}
END_TEST

START_TEST(s21_tolower_test_4) {
#line 623
    char* str = "hello";
    char* ptr = (char*)s21_to_lower(str);
    ck_assert_str_eq(ptr, "hello");
    free(ptr);
}
END_TEST

START_TEST(s21_tolower_test_5) {
#line 628
    char* str = "!@#$%^&";
    char* ptr = (char*)s21_to_lower(str);
    ck_assert_str_eq(ptr, "!@#$%^&");
    free(ptr);
// start insert tests
}
END_TEST

START_TEST(s21_insert_test_1) {
#line 634
    char* str1 = "Helrld";
    char* str2 = "lo Wo";
    char* result = (char*)s21_insert(str1, str2, 3);
    ck_assert_str_eq(result, "Hello World");
    free(result);
}
END_TEST

START_TEST(s21_insert_test_2) {
#line 640
    char* str1 = "Hello";
    char* str2 = " World";
    char* result = (char*)s21_insert(str1, str2, 5);
    ck_assert_str_eq(result, "Hello World");
    free(result);
}
END_TEST

START_TEST(s21_insert_test_3) {
#line 646
    char* str1 = "";
    char* str2 = "Hello World";
    char* result = (char*)s21_insert(str1, str2, 0);
    ck_assert_str_eq(result, "Hello World");
    free(result);
}
END_TEST

START_TEST(s21_trim_test_1) {
#line 652
    char *str = "  123abc456xyz789  ";
    char *ptr = S21_NULL;
    char *result = (char*)s21_trim(str, ptr);
    ck_assert_str_eq(result, "123abc456xyz789");
    free(result);
}
END_TEST

START_TEST(s21_trim_test_2) {
#line 658
    char *str = "123abc456xyz789";
    char *ptr = "123456789";
    char *result = (char*)s21_trim(str, ptr);
    ck_assert_str_eq(result, "abc456xyz");
    free(result);
}
END_TEST

START_TEST(s21_trim_test_3) {
#line 664
    char *str = "";
    char *ptr = "123456789";
    char *result = (char*)s21_trim(str, ptr);
    ck_assert_str_eq(result, "");
    free(result);
}
END_TEST

START_TEST(s21_sprintf_test_1_c) {
#line 670
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %c", 'a'), sprintf(str2, "Hello %c", 'a'));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_c) {
#line 677
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%c", 'a'), sprintf(str2, "%c", 'a'));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_c) {
#line 684
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-5c", 'a'), sprintf(str2, "%-5c", 'a'));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_c) {
#line 691
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%5c", 'a'), sprintf(str2, "%5c", 'a'));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_c) {
#line 698
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%c", 99), sprintf(str2, "%c", 99));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_d) {
#line 705
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %d", 5), sprintf(str2, "Hello %d", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_d) {
#line 712
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%d", 5), sprintf(str2, "%d", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_d) {
#line 719
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%d", -5), sprintf(str2, "%d", -5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_d) {
#line 726
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%+d", 5), sprintf(str2, "%+d", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_d) {
#line 733
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-3d", 5), sprintf(str2, "%-3d", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_d) {
#line 740
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%3d", 5), sprintf(str2, "%3d", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_d) {
#line 747
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*d", 3, 5), sprintf(str2, "%*d", 3, 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_d) {
#line 754
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "% d", -5), sprintf(str2, "% d", -5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_d) {
#line 761
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "% d", 5), sprintf(str2, "% d", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_d) {
#line 768
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%03d", 5), sprintf(str2, "%03d", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_d) {
#line 775
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.3d", 5), sprintf(str2, "%.3d", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_12_d) {
#line 782
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.0d", 0), sprintf(str2, "%.0d", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_13_d) {
#line 789
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*d", 3, 5), sprintf(str2, "%.*d", 3, 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_14_d) {
#line 796
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.0d", 0), sprintf(str2, "%.0d", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_15_d) {
#line 803
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    short int ptr = 2;
    ck_assert_int_eq(s21_sprintf(str1, "%hd", ptr), sprintf(str2, "%hd", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_16_d) {
#line 811
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    long int ptr = 3000000000;
    ck_assert_int_eq(s21_sprintf(str1, "%ld", ptr), sprintf(str2, "%ld", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_i) {
#line 819
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %i", 5), sprintf(str2, "Hello %i", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_i) {
#line 826
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%i", 5), sprintf(str2, "%i", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_i) {
#line 833
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%i", -5), sprintf(str2, "%i", -5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_i) {
#line 840
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%+i", 5), sprintf(str2, "%+i", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_i) {
#line 847
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-3i", 5), sprintf(str2, "%-3i", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_i) {
#line 854
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%3i", 5), sprintf(str2, "%3i", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_i) {
#line 861
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*i", 3, 5), sprintf(str2, "%*i", 3, 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_i) {
#line 868
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "% i", -5), sprintf(str2, "% i", -5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_i) {
#line 875
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "% i", 5), sprintf(str2, "% i", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_i) {
#line 882
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%03i", 5), sprintf(str2, "%03i", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_i) {
#line 889
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.3i", 5), sprintf(str2, "%.3i", 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_12_i) {
#line 896
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.0i", 0), sprintf(str2, "%.0i", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_13_i) {
#line 903
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*i", 3, 5), sprintf(str2, "%.*i", 3, 5));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_14_i) {
#line 910
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.0i", 0), sprintf(str2, "%.0i", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_15_i) {
#line 917
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    short int ptr = 2;
    ck_assert_int_eq(s21_sprintf(str1, "%hi", ptr), sprintf(str2, "%hi", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_16_i) {
#line 925
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    long int ptr = 3000000000;
    ck_assert_int_eq(s21_sprintf(str1, "%li", ptr), sprintf(str2, "%li", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_e) {
#line 933
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %e", 0.001), sprintf(str2, "Hello %e", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_e) {
#line 940
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%e", 0.001), sprintf(str2, "%e", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_e) {
#line 947
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-15e", 0.001), sprintf(str2, "%-15e", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_e) {
#line 954
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%15e", 0.001), sprintf(str2, "%15e", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_e) {
#line 961
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%+e", 0.001), sprintf(str2, "%+e", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_e) {
#line 968
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "% e", 0.001), sprintf(str2, "% e", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_e) {
#line 975
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%015e", 0.001), sprintf(str2, "%015e", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_e) {
#line 982
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*e", 15, 0.001), sprintf(str2, "%*e", 15, 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_e) {
#line 989
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.2e", 0.001), sprintf(str2, "%.2e", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_e) {
#line 996
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*e", 2, 0.001), sprintf(str2, "%.*e", 2, 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_e) {
#line 1003
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    long double ptr = 0.0000000000001;
    ck_assert_int_eq(s21_sprintf(str1, "%Le", ptr), sprintf(str2, "%Le", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_E) {
#line 1011
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %E", 0.001), sprintf(str2, "Hello %E", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_E) {
#line 1018
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%E", 0.001), sprintf(str2, "%E", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_E) {
#line 1025
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-15E", 0.001), sprintf(str2, "%-15E", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_E) {
#line 1032
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%15E", 0.001), sprintf(str2, "%15E", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_E) {
#line 1039
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%+E", 0.001), sprintf(str2, "%+E", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_E) {
#line 1046
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "% E", 0.001), sprintf(str2, "% E", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_E) {
#line 1053
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%015E", 0.001), sprintf(str2, "%015E", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_E) {
#line 1060
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*E", 15, 0.001), sprintf(str2, "%*E", 15, 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_E) {
#line 1067
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.2E", 0.001), sprintf(str2, "%.2E", 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_E) {
#line 1074
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*E", 2, 0.001), sprintf(str2, "%.*E", 2, 0.001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_E) {
#line 1081
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    long double ptr = 0.0000000000001;
    ck_assert_int_eq(s21_sprintf(str1, "%LE", ptr), sprintf(str2, "%LE", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_f) {
#line 1089
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %f", 123.123), sprintf(str2, "Hello %f", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_f) {
#line 1096
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%f", 123.123), sprintf(str2, "%f", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_f) {
#line 1103
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-11f", 123.123), sprintf(str2, "%-11f", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_f) {
#line 1110
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%11f", 123.123), sprintf(str2, "%11f", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_f) {
#line 1117
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%+f", 123.123), sprintf(str2, "%+f", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_f) {
#line 1124
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "% f", 123.123), sprintf(str2, "% f", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_f) {
#line 1131
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%#f", 123.), sprintf(str2, "%#f", 123.));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_f) {
#line 1138
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%011f", 123.123), sprintf(str2, "%011f", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_f) {
#line 1145
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%0*f", 11, 123.123), sprintf(str2, "%0*f", 11, 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_f) {
#line 1152
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*f", 10, 123.123), sprintf(str2, "%*f", 10, 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_f) {
#line 1159
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.4f", 123.123), sprintf(str2, "%.4f", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_12_f) {
#line 1166
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*f", 4, 123.123), sprintf(str2, "%.*f", 4, 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_13_f) {
#line 1173
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    long double ptr = 123.123;
    ck_assert_int_eq(s21_sprintf(str1, "%Lf", ptr), sprintf(str2, "%Lf", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_14_f) {
#line 1181
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    double ptr = 123.123;
    ck_assert_int_eq(s21_sprintf(str1, "%#.0f", ptr), sprintf(str2, "%#.0f", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_g) {
#line 1189
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %g", 123.123), sprintf(str2, "Hello %g", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_g) {
#line 1196
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%g", 123.123), sprintf(str2, "%g", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_g) {
#line 1203
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-11g", 123.123), sprintf(str2, "%-11g", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_g) {
#line 1210
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%11g", 123.123), sprintf(str2, "%11g", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_g) {
#line 1217
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%+g", 123.123), sprintf(str2, "%+g", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_g) {
#line 1224
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "% g", 123.123), sprintf(str2, "% g", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_g) {
#line 1231
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%#g", 123.), sprintf(str2, "%#g", 123.));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_g) {
#line 1238
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%011g", 123.123), sprintf(str2, "%011g", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_g) {
#line 1245
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%0*g", 11, 123.123), sprintf(str2, "%0*g", 11, 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_g) {
#line 1252
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*g", 10, 123.123), sprintf(str2, "%*g", 10, 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_g) {
#line 1259
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.4g", 123.123), sprintf(str2, "%.4g", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_12_g) {
#line 1266
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*g", 4, 123.123), sprintf(str2, "%.*g", 4, 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_13_g) {
#line 1273
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    long double ptr = 123.123;
    ck_assert_int_eq(s21_sprintf(str1, "%Lg", ptr), sprintf(str2, "%Lg", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_14_g) {
#line 1281
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.4g", -123.123), sprintf(str2, "%.4g", -123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_15_g) {
#line 1288
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.4g", 123123123.123), sprintf(str2, "%.4g", 123123123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_16_g) {
#line 1295
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.4g", 0.00000000000001), sprintf(str2, "%.4g", 0.00000000000001));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_17_g) {
#line 1302
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.10g", 123.10000), sprintf(str2, "%.10g", 123.10000));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_G) {
#line 1309
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %G", 123.123), sprintf(str2, "Hello %G", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_G) {
#line 1316
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%G", 123.123), sprintf(str2, "%G", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_G) {
#line 1323
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-11G", 123.123), sprintf(str2, "%-11G", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_G) {
#line 1330
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%11G", 123.123), sprintf(str2, "%11G", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_G) {
#line 1337
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%+G", 123.123), sprintf(str2, "%+G", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_G) {
#line 1344
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "% G", 123.123), sprintf(str2, "% G", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_G) {
#line 1351
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%#G", 123.), sprintf(str2, "%#G", 123.));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_G) {
#line 1358
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%011G", 123.123), sprintf(str2, "%011G", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_G) {
#line 1365
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%0*G", 11, 123.123), sprintf(str2, "%0*G", 11, 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_G) {
#line 1372
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*G", 10, 123.123), sprintf(str2, "%*G", 10, 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_G) {
#line 1379
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.4G", 123.123), sprintf(str2, "%.4G", 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_12_G) {
#line 1386
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*G", 4, 123.123), sprintf(str2, "%.*G", 4, 123.123));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_13_G) {
#line 1393
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    long double ptr = 123.123;
    ck_assert_int_eq(s21_sprintf(str1, "%LG", ptr), sprintf(str2, "%LG", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_14_G) {
#line 1401
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    double ptr = 123123123.123;
    ck_assert_int_eq(s21_sprintf(str1, "%G", ptr), sprintf(str2, "%G", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_o) {
#line 1409
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %o", 10), sprintf(str2, "Hello %o", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_o) {
#line 1416
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%o", 10), sprintf(str2, "%o", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_o) {
#line 1423
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-5oHello", 10), sprintf(str2, "%-5oHello", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_o) {
#line 1430
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%5o", 10), sprintf(str2, "%5o", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_o) {
#line 1437
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%#o", 10), sprintf(str2, "%#o", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_o) {
#line 1444
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%05o", 10), sprintf(str2, "%05o", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_o) {
#line 1451
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%0*o", 5, 10), sprintf(str2, "%0*o", 5, 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_o) {
#line 1458
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*o", 5, 10), sprintf(str2, "%*o", 5, 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_o) {
#line 1465
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.4o", 10), sprintf(str2, "%.4o", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_o) {
#line 1472
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*o", 4, 10), sprintf(str2, "%.*o", 4, 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_o) {
#line 1479
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*o", 0, 0), sprintf(str2, "%.*o", 0, 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_12_o) {
#line 1486
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%#.0o", 0), sprintf(str2, "%#.0o", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_13_o) {
#line 1493
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.0o", 0), sprintf(str2, "%.0o", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_s) {
#line 1500
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %s", "World!"), sprintf(str2, "Hello %s", "World!"));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_s) {
#line 1507
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %.5s", "World!"), sprintf(str2, "Hello %.5s", "World!"));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_s) {
#line 1514
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %.*s", 5, "World!"), sprintf(str2, "Hello %.*s", 5, "World!"));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_u) {
#line 1521
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 5;
    ck_assert_int_eq(s21_sprintf(str1, "Hello %u", ptr), sprintf(str2, "Hello %u", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_u) {
#line 1529
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 5;
    ck_assert_int_eq(s21_sprintf(str1, "%u", ptr), sprintf(str2, "%u", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_u) {
#line 1537
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 5;
    ck_assert_int_eq(s21_sprintf(str1, "%-3u", ptr), sprintf(str2, "%-3u", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_u) {
#line 1545
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 5;
    ck_assert_int_eq(s21_sprintf(str1, "%3u", ptr), sprintf(str2, "%3u", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_u) {
#line 1553
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 5;
    ck_assert_int_eq(s21_sprintf(str1, "%*u", 3, ptr), sprintf(str2, "%*u", 3, ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_u) {
#line 1561
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 5;
    ck_assert_int_eq(s21_sprintf(str1, "%03u", ptr), sprintf(str2, "%03u", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_u) {
#line 1569
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 5;
    ck_assert_int_eq(s21_sprintf(str1, "%.3u", ptr), sprintf(str2, "%.3u", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_u) {
#line 1577
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 0;
    ck_assert_int_eq(s21_sprintf(str1, "%.0u", ptr), sprintf(str2, "%.0u", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_u) {
#line 1585
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 5;
    ck_assert_int_eq(s21_sprintf(str1, "%.*u", 3, ptr), sprintf(str2, "%.*u", 3, ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_u) {
#line 1593
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned int ptr = 0;
    ck_assert_int_eq(s21_sprintf(str1, "%.0u", ptr), sprintf(str2, "%.0u", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_u) {
#line 1601
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned short int ptr = 2;
    ck_assert_int_eq(s21_sprintf(str1, "%hu", ptr), sprintf(str2, "%hu", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_12_u) {
#line 1609
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    unsigned long int ptr = 3000000000;
    ck_assert_int_eq(s21_sprintf(str1, "%lu", ptr), sprintf(str2, "%lu", ptr));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_x) {
#line 1617
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %x", 10), sprintf(str2, "Hello %x", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_x) {
#line 1624
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%x", 10), sprintf(str2, "%x", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_x) {
#line 1631
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-5xHello", 10), sprintf(str2, "%-5xHello", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_x) {
#line 1638
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%5x", 10), sprintf(str2, "%5x", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_x) {
#line 1645
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%#x", 10), sprintf(str2, "%#x", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_x) {
#line 1652
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%05x", 10), sprintf(str2, "%05x", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_x) {
#line 1659
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%0*x", 5, 10), sprintf(str2, "%0*x", 5, 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_x) {
#line 1666
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*x", 5, 10), sprintf(str2, "%*x", 5, 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_x) {
#line 1673
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.4x", 10), sprintf(str2, "%.4x", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_x) {
#line 1680
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*x", 4, 10), sprintf(str2, "%.*x", 4, 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_x) {
#line 1687
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*x", 0, 0), sprintf(str2, "%.*x", 0, 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_12_x) {
#line 1694
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%#.0x", 0), sprintf(str2, "%#.0x", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_13_x) {
#line 1701
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.0x", 0), sprintf(str2, "%.0x", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_X) {
#line 1708
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "Hello %X", 10), sprintf(str2, "Hello %X", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_X) {
#line 1715
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%X", 10), sprintf(str2, "%X", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_3_X) {
#line 1722
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%-5XHello", 10), sprintf(str2, "%-5XHello", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_4_X) {
#line 1729
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%5X", 10), sprintf(str2, "%5X", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_5_X) {
#line 1736
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%#X", 10), sprintf(str2, "%#X", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_6_X) {
#line 1743
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%05X", 10), sprintf(str2, "%05X", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_7_X) {
#line 1750
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%0*X", 5, 10), sprintf(str2, "%0*X", 5, 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_8_X) {
#line 1757
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%*X", 5, 10), sprintf(str2, "%*X", 5, 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_9_X) {
#line 1764
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.4X", 10), sprintf(str2, "%.4X", 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_10_X) {
#line 1771
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*X", 4, 10), sprintf(str2, "%.*X", 4, 10));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_11_X) {
#line 1778
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.*X", 0, 0), sprintf(str2, "%.*X", 0, 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_12_X) {
#line 1785
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%#.0X", 0), sprintf(str2, "%#.0X", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_13_X) {
#line 1792
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%.0X", 0), sprintf(str2, "%.0X", 0));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_p) {
#line 1799
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%p", str1), sprintf(str2, "%p", str1));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_2_p) {
#line 1806
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%5p", str1), sprintf(str2, "%5p", str1));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1_n) {
#line 1813
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    int x = 0;
    int *cnt = &x;
    char *ptr = "Hello %n Hello";
    ck_assert_int_eq(s21_sprintf(str1, ptr, cnt), sprintf(str2, ptr, cnt));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

START_TEST(s21_sprintf_test_1) {
#line 1823
    char *str1 = (char*)malloc(sizeof(char) * 1024);
    char *str2 = (char*)malloc(sizeof(char) * 1024);
    ck_assert_int_eq(s21_sprintf(str1, "%%"), sprintf(str2, "%%"));
    ck_assert_str_eq(str1, str2);
    free(str1);
    free(str2);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_memset_test_1_str);
    tcase_add_test(tc1_1, s21_strchr_test_1);
    tcase_add_test(tc1_1, s21_strchr_test_2);
    tcase_add_test(tc1_1, s21_strchr_test_3);
    tcase_add_test(tc1_1, s21_strchr_test_4);
    tcase_add_test(tc1_1, s21_strchr_test_5);
    tcase_add_test(tc1_1, s21_strchr_test_6);
    tcase_add_test(tc1_1, s21_strcpy_test_1);
    tcase_add_test(tc1_1, s21_strcpy_test_2);
    tcase_add_test(tc1_1, s21_strcpy_test_3);
    tcase_add_test(tc1_1, s21_strcpy_test_4);
    tcase_add_test(tc1_1, s21_strerror_test_1);
    tcase_add_test(tc1_1, s21_strncat_test_1);
    tcase_add_test(tc1_1, s21_strncat_test_2);
    tcase_add_test(tc1_1, s21_strncat_test_3);
    tcase_add_test(tc1_1, s21_strncat_test_4);
    tcase_add_test(tc1_1, s21_strncat_test_5);
    tcase_add_test(tc1_1, s21_strcmp_test_1);
    tcase_add_test(tc1_1, s21_strcmp_test_2);
    tcase_add_test(tc1_1, s21_strcmp_test_3);
    tcase_add_test(tc1_1, s21_strcmp_test_4);
    tcase_add_test(tc1_1, s21_strcmp_test_5);
    tcase_add_test(tc1_1, s21_strspn_test_1);
    tcase_add_test(tc1_1, s21_strspn_test_2);
    tcase_add_test(tc1_1, s21_strspn_test_3);
    tcase_add_test(tc1_1, s21_strspn_test_4);
    tcase_add_test(tc1_1, s21_strspn_test_5);
    tcase_add_test(tc1_1, s21_strstr_test_1);
    tcase_add_test(tc1_1, s21_strstr_test_2);
    tcase_add_test(tc1_1, s21_strstr_test_3);
    tcase_add_test(tc1_1, s21_strstr_test_4);
    tcase_add_test(tc1_1, s21_strtok_test_1);
    tcase_add_test(tc1_1, s21_strtok_test_2);
    tcase_add_test(tc1_1, s21_strtok_test_3);
    tcase_add_test(tc1_1, s21_strtok_test_4);
    tcase_add_test(tc1_1, s21_strtok_test_5);
    tcase_add_test(tc1_1, s21_strtok_test_6);
    tcase_add_test(tc1_1, s21_memchr_test_1_str);
    tcase_add_test(tc1_1, s21_memchr_test_2_str);
    tcase_add_test(tc1_1, s21_memchr_test_3_str);
    tcase_add_test(tc1_1, s21_memchr_test_4_str);
    tcase_add_test(tc1_1, s21_memchr_test_5_str);
    tcase_add_test(tc1_1, s21_memchr_test_6_str);
    tcase_add_test(tc1_1, s21_memcmp_test_1_str);
    tcase_add_test(tc1_1, s21_memcmp_test_2_str);
    tcase_add_test(tc1_1, s21_memcmp_test_3_str);
    tcase_add_test(tc1_1, s21_memcmp_test_4_str);
    tcase_add_test(tc1_1, s21_memcmp_test_5_str);
    tcase_add_test(tc1_1, s21_memcmp_test_6_str);
    tcase_add_test(tc1_1, s21_memcmp_test_7_str);
    tcase_add_test(tc1_1, s21_memmove_test_1_str);
    tcase_add_test(tc1_1, s21_memmove_test_2_str);
    tcase_add_test(tc1_1, s21_memmove_test_3_str);
    tcase_add_test(tc1_1, s21_strcat_test_1_str);
    tcase_add_test(tc1_1, s21_strcat_test_2_str);
    tcase_add_test(tc1_1, s21_strcat_test_3_str);
    tcase_add_test(tc1_1, s21_strcat_test_4_str);
    tcase_add_test(tc1_1, s21_strncmp_test_1);
    tcase_add_test(tc1_1, s21_strncmp_test_2);
    tcase_add_test(tc1_1, s21_strncmp_test_3);
    tcase_add_test(tc1_1, s21_strncmp_test_4);
    tcase_add_test(tc1_1, s21_strncmp_test_5);
    tcase_add_test(tc1_1, s21_strncmp_test_6);
    tcase_add_test(tc1_1, s21_strncmp_test_7);
    tcase_add_test(tc1_1, s21_strncmp_test_8);
    tcase_add_test(tc1_1, s21_strncmp_test_9);
    tcase_add_test(tc1_1, s21_strncmp_test_10);
    tcase_add_test(tc1_1, s21_strncmp_test_11);
    tcase_add_test(tc1_1, s21_strncmp_test_12);
    tcase_add_test(tc1_1, s21_strncmp_test_13);
    tcase_add_test(tc1_1, s21_strncmp_test_14);
    tcase_add_test(tc1_1, s21_strcspn_test_1);
    tcase_add_test(tc1_1, s21_strcspn_test_2);
    tcase_add_test(tc1_1, s21_strcspn_test_3);
    tcase_add_test(tc1_1, s21_strcspn_test_4);
    tcase_add_test(tc1_1, s21_strcspn_test_5);
    tcase_add_test(tc1_1, s21_strcspn_test_6);
    tcase_add_test(tc1_1, s21_strcspn_test_7);
    tcase_add_test(tc1_1, s21_strcspn_test_8);
    tcase_add_test(tc1_1, s21_strrchr_test_1);
    tcase_add_test(tc1_1, s21_strrchr_test_2);
    tcase_add_test(tc1_1, s21_strrchr_test_3);
    tcase_add_test(tc1_1, s21_strrchr_test_4);
    tcase_add_test(tc1_1, s21_strrchr_test_5);
    tcase_add_test(tc1_1, s21_strrchr_test_6);
    tcase_add_test(tc1_1, s21_strrchr_test_7);
    tcase_add_test(tc1_1, s21_strncpy_test_1);
    tcase_add_test(tc1_1, s21_strncpy_test_2);
    tcase_add_test(tc1_1, s21_strncpy_test_3);
    tcase_add_test(tc1_1, s21_strncpy_test_4);
    tcase_add_test(tc1_1, s21_strncpy_test_5);
    tcase_add_test(tc1_1, s21_strncpy_test_6);
    tcase_add_test(tc1_1, s21_strncpy_test_7);
    tcase_add_test(tc1_1, s21_memcpy_test_1);
    tcase_add_test(tc1_1, s21_memcpy_test_2);
    tcase_add_test(tc1_1, s21_memcpy_test_3);
    tcase_add_test(tc1_1, s21_memcpy_test_4);
    tcase_add_test(tc1_1, s21_memcpy_test_5);
    tcase_add_test(tc1_1, s21_memcpy_test_6);
    tcase_add_test(tc1_1, s21_memcpy_test_7);
    tcase_add_test(tc1_1, s21_strlen_test_1);
    tcase_add_test(tc1_1, s21_strlen_test_2);
    tcase_add_test(tc1_1, s21_strlen_test_3);
    tcase_add_test(tc1_1, s21_strlen_test_4);
    tcase_add_test(tc1_1, s21_strpbrk_test_1);
    tcase_add_test(tc1_1, s21_strpbrk_test_2);
    tcase_add_test(tc1_1, s21_strpbrk_test_3);
    tcase_add_test(tc1_1, s21_strpbrk_test_4);
    tcase_add_test(tc1_1, s21_strpbrk_test_5);
    tcase_add_test(tc1_1, s21_strpbrk_test_6);
    tcase_add_test(tc1_1, s21_toupper_test_1);
    tcase_add_test(tc1_1, s21_toupper_test_2);
    tcase_add_test(tc1_1, s21_toupper_test_3);
    tcase_add_test(tc1_1, s21_toupper_test_4);
    tcase_add_test(tc1_1, s21_toupper_test_5);
    tcase_add_test(tc1_1, s21_tolower_test_1);
    tcase_add_test(tc1_1, s21_tolower_test_2);
    tcase_add_test(tc1_1, s21_tolower_test_3);
    tcase_add_test(tc1_1, s21_tolower_test_4);
    tcase_add_test(tc1_1, s21_tolower_test_5);
    tcase_add_test(tc1_1, s21_insert_test_1);
    tcase_add_test(tc1_1, s21_insert_test_2);
    tcase_add_test(tc1_1, s21_insert_test_3);
    tcase_add_test(tc1_1, s21_trim_test_1);
    tcase_add_test(tc1_1, s21_trim_test_2);
    tcase_add_test(tc1_1, s21_trim_test_3);
    tcase_add_test(tc1_1, s21_sprintf_test_1_c);
    tcase_add_test(tc1_1, s21_sprintf_test_2_c);
    tcase_add_test(tc1_1, s21_sprintf_test_3_c);
    tcase_add_test(tc1_1, s21_sprintf_test_4_c);
    tcase_add_test(tc1_1, s21_sprintf_test_5_c);
    tcase_add_test(tc1_1, s21_sprintf_test_1_d);
    tcase_add_test(tc1_1, s21_sprintf_test_2_d);
    tcase_add_test(tc1_1, s21_sprintf_test_3_d);
    tcase_add_test(tc1_1, s21_sprintf_test_4_d);
    tcase_add_test(tc1_1, s21_sprintf_test_5_d);
    tcase_add_test(tc1_1, s21_sprintf_test_6_d);
    tcase_add_test(tc1_1, s21_sprintf_test_7_d);
    tcase_add_test(tc1_1, s21_sprintf_test_8_d);
    tcase_add_test(tc1_1, s21_sprintf_test_9_d);
    tcase_add_test(tc1_1, s21_sprintf_test_10_d);
    tcase_add_test(tc1_1, s21_sprintf_test_11_d);
    tcase_add_test(tc1_1, s21_sprintf_test_12_d);
    tcase_add_test(tc1_1, s21_sprintf_test_13_d);
    tcase_add_test(tc1_1, s21_sprintf_test_14_d);
    tcase_add_test(tc1_1, s21_sprintf_test_15_d);
    tcase_add_test(tc1_1, s21_sprintf_test_16_d);
    tcase_add_test(tc1_1, s21_sprintf_test_1_i);
    tcase_add_test(tc1_1, s21_sprintf_test_2_i);
    tcase_add_test(tc1_1, s21_sprintf_test_3_i);
    tcase_add_test(tc1_1, s21_sprintf_test_4_i);
    tcase_add_test(tc1_1, s21_sprintf_test_5_i);
    tcase_add_test(tc1_1, s21_sprintf_test_6_i);
    tcase_add_test(tc1_1, s21_sprintf_test_7_i);
    tcase_add_test(tc1_1, s21_sprintf_test_8_i);
    tcase_add_test(tc1_1, s21_sprintf_test_9_i);
    tcase_add_test(tc1_1, s21_sprintf_test_10_i);
    tcase_add_test(tc1_1, s21_sprintf_test_11_i);
    tcase_add_test(tc1_1, s21_sprintf_test_12_i);
    tcase_add_test(tc1_1, s21_sprintf_test_13_i);
    tcase_add_test(tc1_1, s21_sprintf_test_14_i);
    tcase_add_test(tc1_1, s21_sprintf_test_15_i);
    tcase_add_test(tc1_1, s21_sprintf_test_16_i);
    tcase_add_test(tc1_1, s21_sprintf_test_1_e);
    tcase_add_test(tc1_1, s21_sprintf_test_2_e);
    tcase_add_test(tc1_1, s21_sprintf_test_3_e);
    tcase_add_test(tc1_1, s21_sprintf_test_4_e);
    tcase_add_test(tc1_1, s21_sprintf_test_5_e);
    tcase_add_test(tc1_1, s21_sprintf_test_6_e);
    tcase_add_test(tc1_1, s21_sprintf_test_7_e);
    tcase_add_test(tc1_1, s21_sprintf_test_8_e);
    tcase_add_test(tc1_1, s21_sprintf_test_9_e);
    tcase_add_test(tc1_1, s21_sprintf_test_10_e);
    tcase_add_test(tc1_1, s21_sprintf_test_11_e);
    tcase_add_test(tc1_1, s21_sprintf_test_1_E);
    tcase_add_test(tc1_1, s21_sprintf_test_2_E);
    tcase_add_test(tc1_1, s21_sprintf_test_3_E);
    tcase_add_test(tc1_1, s21_sprintf_test_4_E);
    tcase_add_test(tc1_1, s21_sprintf_test_5_E);
    tcase_add_test(tc1_1, s21_sprintf_test_6_E);
    tcase_add_test(tc1_1, s21_sprintf_test_7_E);
    tcase_add_test(tc1_1, s21_sprintf_test_8_E);
    tcase_add_test(tc1_1, s21_sprintf_test_9_E);
    tcase_add_test(tc1_1, s21_sprintf_test_10_E);
    tcase_add_test(tc1_1, s21_sprintf_test_11_E);
    tcase_add_test(tc1_1, s21_sprintf_test_1_f);
    tcase_add_test(tc1_1, s21_sprintf_test_2_f);
    tcase_add_test(tc1_1, s21_sprintf_test_3_f);
    tcase_add_test(tc1_1, s21_sprintf_test_4_f);
    tcase_add_test(tc1_1, s21_sprintf_test_5_f);
    tcase_add_test(tc1_1, s21_sprintf_test_6_f);
    tcase_add_test(tc1_1, s21_sprintf_test_7_f);
    tcase_add_test(tc1_1, s21_sprintf_test_8_f);
    tcase_add_test(tc1_1, s21_sprintf_test_9_f);
    tcase_add_test(tc1_1, s21_sprintf_test_10_f);
    tcase_add_test(tc1_1, s21_sprintf_test_11_f);
    tcase_add_test(tc1_1, s21_sprintf_test_12_f);
    tcase_add_test(tc1_1, s21_sprintf_test_13_f);
    tcase_add_test(tc1_1, s21_sprintf_test_14_f);
    tcase_add_test(tc1_1, s21_sprintf_test_1_g);
    tcase_add_test(tc1_1, s21_sprintf_test_2_g);
    tcase_add_test(tc1_1, s21_sprintf_test_3_g);
    tcase_add_test(tc1_1, s21_sprintf_test_4_g);
    tcase_add_test(tc1_1, s21_sprintf_test_5_g);
    tcase_add_test(tc1_1, s21_sprintf_test_6_g);
    tcase_add_test(tc1_1, s21_sprintf_test_7_g);
    tcase_add_test(tc1_1, s21_sprintf_test_8_g);
    tcase_add_test(tc1_1, s21_sprintf_test_9_g);
    tcase_add_test(tc1_1, s21_sprintf_test_10_g);
    tcase_add_test(tc1_1, s21_sprintf_test_11_g);
    tcase_add_test(tc1_1, s21_sprintf_test_12_g);
    tcase_add_test(tc1_1, s21_sprintf_test_13_g);
    tcase_add_test(tc1_1, s21_sprintf_test_14_g);
    tcase_add_test(tc1_1, s21_sprintf_test_15_g);
    tcase_add_test(tc1_1, s21_sprintf_test_16_g);
    tcase_add_test(tc1_1, s21_sprintf_test_17_g);
    tcase_add_test(tc1_1, s21_sprintf_test_1_G);
    tcase_add_test(tc1_1, s21_sprintf_test_2_G);
    tcase_add_test(tc1_1, s21_sprintf_test_3_G);
    tcase_add_test(tc1_1, s21_sprintf_test_4_G);
    tcase_add_test(tc1_1, s21_sprintf_test_5_G);
    tcase_add_test(tc1_1, s21_sprintf_test_6_G);
    tcase_add_test(tc1_1, s21_sprintf_test_7_G);
    tcase_add_test(tc1_1, s21_sprintf_test_8_G);
    tcase_add_test(tc1_1, s21_sprintf_test_9_G);
    tcase_add_test(tc1_1, s21_sprintf_test_10_G);
    tcase_add_test(tc1_1, s21_sprintf_test_11_G);
    tcase_add_test(tc1_1, s21_sprintf_test_12_G);
    tcase_add_test(tc1_1, s21_sprintf_test_13_G);
    tcase_add_test(tc1_1, s21_sprintf_test_14_G);
    tcase_add_test(tc1_1, s21_sprintf_test_1_o);
    tcase_add_test(tc1_1, s21_sprintf_test_2_o);
    tcase_add_test(tc1_1, s21_sprintf_test_3_o);
    tcase_add_test(tc1_1, s21_sprintf_test_4_o);
    tcase_add_test(tc1_1, s21_sprintf_test_5_o);
    tcase_add_test(tc1_1, s21_sprintf_test_6_o);
    tcase_add_test(tc1_1, s21_sprintf_test_7_o);
    tcase_add_test(tc1_1, s21_sprintf_test_8_o);
    tcase_add_test(tc1_1, s21_sprintf_test_9_o);
    tcase_add_test(tc1_1, s21_sprintf_test_10_o);
    tcase_add_test(tc1_1, s21_sprintf_test_11_o);
    tcase_add_test(tc1_1, s21_sprintf_test_12_o);
    tcase_add_test(tc1_1, s21_sprintf_test_13_o);
    tcase_add_test(tc1_1, s21_sprintf_test_1_s);
    tcase_add_test(tc1_1, s21_sprintf_test_2_s);
    tcase_add_test(tc1_1, s21_sprintf_test_3_s);
    tcase_add_test(tc1_1, s21_sprintf_test_1_u);
    tcase_add_test(tc1_1, s21_sprintf_test_2_u);
    tcase_add_test(tc1_1, s21_sprintf_test_3_u);
    tcase_add_test(tc1_1, s21_sprintf_test_4_u);
    tcase_add_test(tc1_1, s21_sprintf_test_5_u);
    tcase_add_test(tc1_1, s21_sprintf_test_6_u);
    tcase_add_test(tc1_1, s21_sprintf_test_7_u);
    tcase_add_test(tc1_1, s21_sprintf_test_8_u);
    tcase_add_test(tc1_1, s21_sprintf_test_9_u);
    tcase_add_test(tc1_1, s21_sprintf_test_10_u);
    tcase_add_test(tc1_1, s21_sprintf_test_11_u);
    tcase_add_test(tc1_1, s21_sprintf_test_12_u);
    tcase_add_test(tc1_1, s21_sprintf_test_1_x);
    tcase_add_test(tc1_1, s21_sprintf_test_2_x);
    tcase_add_test(tc1_1, s21_sprintf_test_3_x);
    tcase_add_test(tc1_1, s21_sprintf_test_4_x);
    tcase_add_test(tc1_1, s21_sprintf_test_5_x);
    tcase_add_test(tc1_1, s21_sprintf_test_6_x);
    tcase_add_test(tc1_1, s21_sprintf_test_7_x);
    tcase_add_test(tc1_1, s21_sprintf_test_8_x);
    tcase_add_test(tc1_1, s21_sprintf_test_9_x);
    tcase_add_test(tc1_1, s21_sprintf_test_10_x);
    tcase_add_test(tc1_1, s21_sprintf_test_11_x);
    tcase_add_test(tc1_1, s21_sprintf_test_12_x);
    tcase_add_test(tc1_1, s21_sprintf_test_13_x);
    tcase_add_test(tc1_1, s21_sprintf_test_1_X);
    tcase_add_test(tc1_1, s21_sprintf_test_2_X);
    tcase_add_test(tc1_1, s21_sprintf_test_3_X);
    tcase_add_test(tc1_1, s21_sprintf_test_4_X);
    tcase_add_test(tc1_1, s21_sprintf_test_5_X);
    tcase_add_test(tc1_1, s21_sprintf_test_6_X);
    tcase_add_test(tc1_1, s21_sprintf_test_7_X);
    tcase_add_test(tc1_1, s21_sprintf_test_8_X);
    tcase_add_test(tc1_1, s21_sprintf_test_9_X);
    tcase_add_test(tc1_1, s21_sprintf_test_10_X);
    tcase_add_test(tc1_1, s21_sprintf_test_11_X);
    tcase_add_test(tc1_1, s21_sprintf_test_12_X);
    tcase_add_test(tc1_1, s21_sprintf_test_13_X);
    tcase_add_test(tc1_1, s21_sprintf_test_1_p);
    tcase_add_test(tc1_1, s21_sprintf_test_2_p);
    tcase_add_test(tc1_1, s21_sprintf_test_1_n);
    tcase_add_test(tc1_1, s21_sprintf_test_1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
